# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: ZDY5NTEwZmUzMTA4ODMyNmE0ODQxOWY0OTQzNTMyYjU2MDNjYjcyZWI3OTZhZTgyNGJiYWRjZjM1Y2Q1OTllYmQ2NDdlNjYyYjgzZmRkOWRjZGQ0OTkzZTc5NzZmY2I5YjhkZjBhNzBjNDJhYzI0MTI3ZTAwMGE1MDIyNmZhNjM=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
