# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
version: '3.8'
services:
  gateway-postgresql:
    image: postgres:14.2
    # volumes:
    #   - ~/volumes/jhipster/gateway/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 5432:5432
